INSERT INTO tutorial (titulo, descripcion, publicado) VALUES
('Aprende Spring Boot desde cero', 'Curso completo para principiantes en Spring Boot, cubriendo desde configuración hasta despliegue.', TRUE),
('Introducción a JPA y Hibernate', 'Explica cómo usar JPA y Hibernate para manejar la persistencia de datos en aplicaciones Java.', FALSE),
('Creación de APIs REST con Spring', 'Aprende a construir APIs REST eficientes y escalables usando Spring Framework.', TRUE),
('Seguridad en aplicaciones web', 'Implementa autenticación y autorización en tus aplicaciones web con Spring Security.', FALSE),
('Microservicios con Spring Cloud', 'Curso avanzado sobre cómo diseñar y desplegar microservicios utilizando Spring Cloud.', TRUE),
('Gestión de bases de datos en Java', 'Técnicas y mejores prácticas para la gestión de bases de datos usando JDBC y JPA.', FALSE),
('Testing en Spring Boot', 'Aprende a escribir pruebas unitarias y de integración en aplicaciones Spring Boot.', TRUE),
('Optimización de aplicaciones Java', 'Mejora el rendimiento de tus aplicaciones Java con técnicas de profiling y optimización.', FALSE),
('Spring Boot y Docker', 'Integración de Spring Boot con Docker para facilitar el despliegue y la escalabilidad.', TRUE),
('Programación reactiva con Spring', 'Introduce los conceptos de programación reactiva y cómo implementarlos en Spring.', FALSE),
('Desarrollo de front-end para Spring', 'Cómo integrar tecnologías de front-end como Angular o React con aplicaciones Spring.', TRUE),
('Spring Boot y Kubernetes', 'Despliega tus aplicaciones Spring Boot en un entorno de Kubernetes.', FALSE),
('Uso de cachés en Spring', 'Implementa cachés en tus aplicaciones Spring para mejorar el rendimiento y la escalabilidad.', TRUE),
('Internacionalización de aplicaciones', 'Aprende a hacer tus aplicaciones accesibles para un público global con múltiples idiomas.', FALSE),
('Arquitectura limpia en Java', 'Aplica los principios de arquitectura limpia en tus proyectos Java para mejorar la mantenibilidad.', TRUE),
('Mejores prácticas en APIs REST', 'Aprende las mejores prácticas para diseñar y mantener APIs REST.', FALSE),
('Eventos y mensajería en Spring', 'Manejo de eventos y mensajería asíncrona con Spring Events y RabbitMQ.', TRUE),
('Automatización de procesos con Spring', 'Automatiza tareas y procesos en tus aplicaciones con Spring Batch y Spring Scheduler.', FALSE),
('Acceso a datos NoSQL en Spring', 'Integración de bases de datos NoSQL como MongoDB y Cassandra en aplicaciones Spring.', TRUE),
('Spring Boot en la nube', 'Configura y despliega aplicaciones Spring Boot en servicios en la nube como AWS y Azure.', FALSE),
('Uso avanzado de Spring Data JPA', 'Profundiza en características avanzadas de Spring Data JPA para un manejo más eficiente de la persistencia.', TRUE),
('Seguridad avanzada con OAuth2', 'Implementa OAuth2 y OpenID Connect en tus aplicaciones Spring para una seguridad robusta.', FALSE),
('WebSockets en Spring', 'Implementa comunicación en tiempo real en tus aplicaciones web con Spring WebSockets.', TRUE),
('Spring y el patrón Reactive', 'Utiliza el patrón Reactive en Spring para manejar grandes volúmenes de datos de forma eficiente.', FALSE),
('Pruebas de carga en Spring', 'Aprende a realizar pruebas de carga y stress para asegurar la escalabilidad de tus aplicaciones.', TRUE),
('Personalización de Spring Boot', 'Cómo personalizar y extender Spring Boot para ajustarse a necesidades específicas.', FALSE),
('Control de transacciones en Spring', 'Gestiona transacciones de manera efectiva en aplicaciones empresariales con Spring.', TRUE),
('Integración continua con Spring Boot', 'Configura pipelines de CI/CD para aplicaciones Spring Boot con Jenkins y GitLab.', FALSE),
('Uso de GraphQL en Spring', 'Implementa APIs usando GraphQL en Spring para ofrecer una alternativa a REST.', TRUE),
('Monitoreo de aplicaciones Spring', 'Utiliza herramientas como Spring Boot Actuator y Prometheus para monitorear tus aplicaciones.', FALSE),
('Desarrollo dirigido por eventos en Spring', 'Implementa arquitecturas dirigidas por eventos en tus aplicaciones con Spring Cloud Stream.', TRUE),
('Spring y Machine Learning', 'Integración de modelos de Machine Learning en aplicaciones Spring.', FALSE),
('Microservicios escalables con Spring', 'Construye microservicios escalables y resilientes con Spring Boot y Spring Cloud.', TRUE),
('Desarrollo de juegos en Java', 'Introduce el desarrollo de videojuegos en Java utilizando librerías como LibGDX.', FALSE),
('Java avanzado para desarrolladores de Spring', 'Aprende características avanzadas de Java que pueden potenciar tus aplicaciones Spring.', TRUE),
('Spring Boot para aplicaciones móviles', 'Desarrolla backends para aplicaciones móviles usando Spring Boot.', FALSE),
('Spring y API Gateway', 'Configura un API Gateway en tu arquitectura de microservicios con Spring Cloud Gateway.', TRUE),
('Autenticación multifactor en Spring', 'Añade una capa extra de seguridad con autenticación multifactor en tus aplicaciones Spring.', FALSE),
('Persistencia políglota en Spring', 'Gestiona múltiples fuentes de datos en una sola aplicación con Spring Data.', TRUE),
('Spring Framework y Blockchain', 'Integra tecnología blockchain en tus aplicaciones Java utilizando Spring Boot.', FALSE),
('Manejo de errores en Spring', 'Mejora el manejo de errores en tus aplicaciones para proporcionar una mejor experiencia de usuario.', TRUE),
('Integración de microservicios con Istio', 'Utiliza Istio para manejar la comunicación entre microservicios en aplicaciones Spring.', FALSE),
('Desarrollo de CLI con Spring Shell', 'Crea aplicaciones de línea de comandos interactivas con Spring Shell.', TRUE),
('Spring y el Internet de las Cosas', 'Desarrolla aplicaciones para el Internet de las Cosas (IoT) con Spring Framework.', FALSE),
('Optimización de JVM para Spring', 'Técnicas para optimizar la JVM para aplicaciones Spring.', TRUE),
('Spring Boot y React', 'Desarrolla aplicaciones completas con Spring Boot en el backend y React en el frontend.', FALSE),
('Escalabilidad en Spring Cloud', 'Estrategias para escalar aplicaciones desplegadas en Spring Cloud.', TRUE),
('Spring Boot y Micro Frontends', 'Integra la arquitectura de micro frontends en tus aplicaciones con Spring Boot.', FALSE),
('Java Records en Spring', 'Aprovecha las ventajas de Java Records en aplicaciones Spring para una mayor claridad y eficiencia en el código.', TRUE),
('Multitenancy en Spring Boot', 'Implementa aplicaciones multi-tenancy utilizando técnicas avanzadas en Spring Boot.', FALSE);
